version: '3.1'

services:
  postgresql:
    image: postgres:11
    ports:
      - "5432:5432"
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=survey_results
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
